name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd x86_64/ && docker build . --file Dockerfile-slim --tag mboyar/dev-env-linux-kernel-rust:$(date +%s)
